### ISSUE TITLE
add support for env command 

### ISSUE THREAD

**Issue by neillturner** [cake-contrib/Cake.Terraform#26]
see example: 
 https://github.com/skyscrapers/terraform-env-test

terraform env new staging
terraform plan
terraform apply
terraform plan

it would be great if we could do the env command as it will be a common requirement to support multiple environments ie. test, staging, prod as that's the whole point of using cake to automate that. I will see if i can work up a PR

**Comment by neillturner** [comment]
written some code. how do i build and test.?
tried running the build.ps1 but get error:

```
DotNetCore-Restore
========================================
Executing task: DotNetCore-Restore
An error occurred when executing task 'DotNetCore-Restore'.  
```
so i must be missing something

**Comment by erikvanbrakel** [comment]
Hmm, not sure. Do you have .NET core installed? That could be a requirement. I'm using https://github.com/cake-contrib/Cake.Recipe for building this, so it could be there's some hidden dependencies I'm not aware of.

If you figure it out, let me know so I can drop it in the Readme file.

**Comment by erikvanbrakel** [comment]
Also, keep an eye on this:
https://github.com/hashicorp/terraform/pull/14952 They renamed environments to workspaces in 0.10.

**Comment by neillturner** [comment]
Created PR Terraform Env Support #28
I suggest  releasing this and them moving it on to workspaces when they change that and releasing a new version of your plugin. 

I suggest you need to have a way for the plugin to have a dependency on version of terraform somehow.    
In my ruby plugins (see https://rubygems.org/gems/kitchen-ansible) I can set min and max version of dependencies plus semantic version dependencies. 

I guess you need to do a 'terraform version' command and check it meets the dependency requirements of your plugin version.

**Comment by neillturner** [comment]
need .NET Core installed: 
https://www.microsoft.com/net/core#windowscmd

**Comment by erikvanbrakel** [comment]
As it's unclear when they will release TF 0.10, I agree. With TF changing their backwards compatibility now and then, I think I'm going to have to decide what I want to do with that. Hopefully it'll be easy to work around the differences.

**Comment by damianh** [comment]
I wouldn't bother with attempting to support previous versions of terraform until they get to release 1.0 themselves (and start applying Semver to themselves). Until then, target the latest. IMHO.
