### ISSUE TITLE
Cake Contrib

### ISSUE THREAD

**Issue by JeremyCade** [cake-contrib/Cake.Terraform#38]
@erikvanbrakel would it be possible to migrate this project to the Cake Contrib org?

**Comment by gep13** [comment]
@erikvanbrakel what are your thoughts on this?  Thanks

**Comment by gep13** [comment]
@JeremyCade this has now been completed.  Huge thanks to @erikvanbrakel for allowing the transfer to happen.

**Comment by damianh** [comment]
Nice one @erikvanbrakel
