### ISSUE TITLE
Cake.Recipe... any feedback?

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Terraform#4]
Couldn't help but notice that you are using Cake.Recipe.  There is little to no documentation around this yet, as I haven't gotten around to using it, and I just wanted to get some feedback from yourself about it's usage.  Good?  Bad?  WTF?

Cheers!

**Comment by gep13** [comment]
@erikvanbrakel ^^

**Comment by erikvanbrakel** [comment]
@gep13 When you get everything working it's really nice. But the lack of documentation is a big hurdle, definitely! I had to dig through code to figure out the wyam stuff, and how and when certain build steps are skipped. I also used the other repos in cake-contrib to figure out what those are doing to get everything working.

__Good__:
 - Takes care of everything
 - If addin repos all follow this format, it's easy to navigate them once you know the pattern
 - Helps devs to write documentation, as the publishing part is dealt with and it feels nice to have a fancy manual site

__Bad__:
 - Difficult to figure out what parameters to set. Could use a list of available environment variables for instance
 - Difficult to figure out when certain steps run (or get skipped). I think this is a nice candidate for a flowchart or similar
 - Step-by-step tutorial on how to get from zero to hero would be nice:
    1. Minimal code for an addin
    2. How to set up docs
    3. How to set up nuget publishing
    4. How to add your addin to the cake addin list
    5. etc. etc.

**Comment by gep13** [comment]
Yip, that perhaps much sums up what i expected 😄 

Docs are on my list, just need to get a few other things out the way first.

>@erikvanbrakel said...
If addin repos all follow this format, it's easy to navigate them once you know the pattern

This is what i am working towards in the cake-contrib org.

>@erikvanbrakel said...
I think this is a nice candidate for a flowchart or similar

Great idea!

**Comment by gep13** [comment]
@erikvanbrakel I have started the process of doing the documentation:

https://cake-contrib.github.io/Cake.Recipe/docs/fundamentals/environment-variables

Any additional feedback that you have will be welcomed, thanks!
