### ISSUE TITLE
Support Terraform Validate

### ISSUE THREAD

**Issue by kevbite** [cake-contrib/Cake.Terraform#57]
It'd be nice if the `Cake.Terraform` could support `terraform validate` so that we can do basic checks on our CI integration before packaging up the scripts.

https://www.terraform.io/docs/commands/validate.html

**Comment by pascalberger** [comment]
Agree, this would work nice together with [Cake.Issues.Terraform](https://github.com/cake-contrib/Cake.Issues.Terraform), which can parse the output from `terraform validate -json` for further processing, build breaking, reporting to pull requests or reporting.
