### ISSUE TITLE
Is this repo abbandoned?

### ISSUE THREAD

**Issue by jedielson** [cake-contrib/Cake.Terraform#62]
The last commit was about two years ago and there's three PRs open.

Is anyone mantaining it?
How can we help in next moviments?

**Comment by gep13** [comment]
@jedielson not abandoned, no. Perhaps better to say not prioritised. This addin lives in the cake-contrib Organization, so if you are interested in helping out, we can make that happen.

**Comment by garywoodfine** [comment]
Looks like nothing has been _prioritised_ on this repo for 5 years now.  Seems a couple of PR's are awaiting approval for 3 years now.   Is it safe to call it abandoned yet ?  (joke)

In all seriousness I think there is an issue with the library,  because tried to use the plugin today, and falls over at the first hurdle:
```csharp
#addin nuget:?package=Cake.Terraform&version=0.11.0

var target = Argument("target", "Default");

Task("Init")
  .Description("execute Terraform init ")
  .Does(() => {   
   
     var settings = new TerraformInitSettings{
         WorkingDirectory = "./terraform"
     };
      TerraformInit(settings);
  });
 Task("Default")
    .IsDependentOn("Init");
  
  RunTarget(target);
```


```shell
 dotnet cake terraform.cake 
The assembly 'Cake.Terraform, Version=0.11.0.0, Culture=neutral, PublicKeyToken=null' 
is referencing an older version of Cake.Core (0.33.0). 
For best compatibility it should target Cake.Core version 4.0.0.

/terraform.cake(9,25): error CS0246: The type or namespace name 'TerraformInitSettings' could not be found (are you missing a using directive or an assembly reference?)
Error: Error(s) occurred when compiling build script:
/terraform.cake(9,25): error CS0246: The type or namespace name 'TerraformInitSettings' could not be found (are you missing a using directive or an assembly reference?)
```
 Seems it requires updating to Cake.Core version 4.0.0,   but no PR's have been approved in years so a bit reluctant to put in the effort to update the plugin.

**Comment by nils-a** [comment]
I'm going to have a look at the existing PRs and merge them in. After that, I'll update the repo a bit.
Then I'll release versions for Cake 1.0, 2.0, 3.0 and 4.0.

It might take some days, though.

As @gep13 said: This repo is definitively not abandoned. It simply didn't get much love for some time.

I'll go ahead and close this issue, don't hesitate to comment if more questions arise.
