### ISSUE TITLE
Net Standard 1.6

### ISSUE THREAD

**Issue by Jonesie** [cake-contrib/Cake.Terraform#9]
Hi.  Any chance you can make a .Net Core version ?

  Installing Cake.Terraform 0.2.0.
C:\Program Files\dotnet\sdk\1.0.1\NuGet.targets(97,5): error : Package Cake.Terraform 0.2.0 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package Cake.Terraform 0.2.0 supports: net45 (.NETFramework,Version=v4.5)

**Comment by erikvanbrakel** [comment]
Sure, I'll take a look. Didn't do that before, but I believe just changing to the new csproj and adding multiple target frameworks should do the trick.

**Comment by erikvanbrakel** [comment]
Problem. Cake.Terraform depends on Cake.Recipe, which has no support for the new csproj format yet. https://github.com/cake-contrib/Cake.Recipe/issues/10

I'll leave this open and will continue when it's supported.

**Comment by erikvanbrakel** [comment]
https://github.com/cake-contrib/Cake.Recipe/issues/87

**Comment by erikvanbrakel** [comment]
@Jonesie could you see if https://www.myget.org/feed/erikvanbrakel/package/nuget/Cake.Terraform/0.5.0-unstable0006 works for you?

**Comment by erikvanbrakel** [comment]
Closing this due to lack of response. I'm assuming it works.
